### ISSUE TITLE
You specified `onScroll` on a <ScrollView> but not `scrollEventThrottle`. You will only receive one event. Using `16` you get all the events but be aware that it may cause frame drops, use a bigger number if you don't need as much precision.

### ISSUE THREAD

**Issue by binhhong1412** [mikezzb/react-native-timetable#3]
When I scroll the time table horizontally, the console.log outputs this. But the app itself works completely fine.

I suggest: if the whole table can be seen in one screen (e.g. on Iphone X, 'numOfDays' & 'numOfDaysPerPage' = 6), then the timetable automatically disables the Horizontal Scroll (it's useless since we can already see the whole table in one screen).

By the way if 'numOfDays' is larger than 'numOfDaysPerPage', when I scroll horizontally the header is delayed comparing to the contents of the time table. Example: https://user-images.githubusercontent.com/108684521/184282284-bf47a26a-b7ad-4348-adc4-f559bb7209dc.mp4

**Comment by mikezzb** [comment]
Hi, thank you so much for your report. Shall be fixed in 0.2.5
